#ifndef globais

// 33 35 37 39 41 40
// PC1, PC3, PC5, PC7, PC8, PC9,
// mapeamento na placa: ESQUERDA, FRENTE, SAIDA, DIREITA, T1,T2
#define SENSOR_FRENTE IOPORT_CREATE_PIN(PIOC, 3)
#define SENSOR_ESQUERDA IOPORT_CREATE_PIN(PIOC, 1)
#define SENSOR_DIREITA IOPORT_CREATE_PIN(PIOC, 5)
#define SENSOR_SAIDA IOPORT_CREATE_PIN(PIOC, 7)
#define SENSOR_TRAS1 IOPORT_CREATE_PIN(PIOC, 8)
#define SENSOR_TRAS2 IOPORT_CREATE_PIN(PIOC, 9)

typedef enum
{
	STATE_DISCONNECTED,
	STATE_STANDBY,
	STATE_MOVING_FORWARD,
	STATE_TURNING_LEFT,
	STATE_TURNING_RIGHT,
	STATE_MOVING_REVERSE,
	NUM_STATES
}StateType;
uint32_t volatile result_adc;
// Function Pointer for State Machines
extern StateType SmState;

#endif